[versions]
#commands = "11.0.0"
#config = "4.6.3"
#metrics = "3.1.0"


kotlin = "2.1.20"
#shadow = "9.1.0"

paper = "2.0.0-beta.18"
nova = "0.0.8"

yml = "0.8.0"

[libraries]
#commands = { module = "dev.jorel:commandapi-paper-shade", version.ref = "commands" }
#config = { module = "de.exlll:configlib-yaml", version.ref = "config" }
#metrics = { module = "org.bstats:bstats-bukkit", version.ref = "metrics" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
#shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

paper = { id = "io.papermc.paperweight.userdev", version.ref = "paper" }
nova = { id = "com.undefinedcreations.nova", version.ref = "nova" }

yml = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "yml" }
